version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2.14
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    environment:
      - REDIS_PORT=${REDIS_PORT}

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}:0:${REDIS_PASSWORD}
      - PORT=8081
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081

  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'mysql-vol:/var/lib/mysql'

  db-tool:
    container_name: db-tool
    image: adminer:latest
    restart: always
    ports:
      - ${DB_TOOL_PORT:-8082}:8080

  loki:
    container_name: loki
    image: grafana/loki:2.9.6
    command: -config.file=/etc/loki/config.yaml
    volumes:
      # - loki-vol:/loki
      - "./deploy/docker/loki/config.yaml:/etc/loki/config.yaml"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.1
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
      # - GF_SERVER_SERVE_FROM_SUB_PATH=true
      # - GF_SERVER_ROOT_URL=http://domain.com/grafana
    volumes:
      # - ./volumes/grafana/data:/var/lib/grafana
      # - ./volumes/grafana/log:/var/log/grafana
      - "./deploy/docker/grafana/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml"

volumes:
  mysql-vol:
    driver: local
  # loki-vol:
  #   driver: local