version: '3'
services:
  redis:
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}

  db:
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
  
  loki:
    ports:
      - "3100:3100"

  grafana:
    ports:
      - "3333:3000"