version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2.14
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    environment:
      - REDIS_PORT=${REDIS_PORT}

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}:0:${REDIS_PASSWORD}
      - PORT=8081
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081

  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'mysql-vol:/var/lib/mysql'

  db-tool:
    container_name: db-tool
    image: adminer:latest
    restart: always
    ports:
      - ${DB_TOOL_PORT:-8082}:8080

volumes:
  mysql-vol:
    driver: local