version: '3'
services:
  redis:
    container_name: redis
    image: redis:6.2.14
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    environment:
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - redis
      - backend

  db:
    container_name: db
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'mysql-vol:/var/lib/mysql'
    networks:
      - db
      - backend

volumes:
  mysql-vol:
    driver: local

networks:
  backend:
  db:
  redis: