version: '3'
services:
  app:
    container_name: app
    image: login-manager
    build:
      context: .
      dockerfile: dockerfile
      target: deploy
      args:
        - APP_ENV=${APP_ENV}
    restart: unless-stopped
    ports:
      - 3000:${PORT:-3000}
    volumes:
      - './logs/dev:/var/log/login-manager'

  redis:
    extends:
      file: docker-compose.infra.yml
      service: redis
  
  db:
    extends:
      file: docker-compose.infra.yml
      service: db

volumes:
  mysql-vol:
    driver: local