export enum ErrorCode {
  SUCCESS = 'OK',
  TIMEOUT = '%s執行時間過長，強制中斷，請確認服務或網路是否正常',
  PROCESSING = '執行中',
  LOGIN_FAIL = '登入失敗',
  SETTING_FAIL = '%s設定失敗',
  SYSTEM_FAIL = '系統錯誤',
  VAILD_FAIL = '驗證失敗',
  NOT_FOUND = '查無資料',
  EXEC_FAIL = '執行失敗',
  EXISTING = '已存在',
  WRONG_INPUT = '參數錯誤',
  PAST_DATE = '輸入過去時間',
  CACHED = '資料未變動',
  CONNECT_OVERLAP = '連線時間與連線結束時間不得於未批核連線區間之中，且連線時間不得與核准連線時間相同',
}
