FROM node:20-alpine AS base

RUN npm i -g pnpm &&\
    pnpm i dos2unix &&\
    apk update && apk add bash


FROM base As dependencies

WORKDIR /app
COPY ./package.json ./pnpm-lock.yaml ./
RUN pnpm install


FROM base As build

ARG APP_ENV

WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN /bin/bash ./script/load-config.bash $APP_ENV &&\
    pnpm build


FROM base As deploy

WORKDIR /app
COPY --from=build /app/public ./public
COPY --from=build /app/.env .env
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

CMD HOSTNAME="0.0.0.0" node server.js
